---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-cloudfare
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hotanloc2001@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: hotanloc2001@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "domain.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  cloudflare-token: CzxxqelSjUdDF4FXLAgKb2Z9WWkqbJZXWajLRQS5 # Lấy API key ở đây https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens

