apiVersion: v1
kind: Namespace
metadata:
  name: app-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-deploy
  namespace: app-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
        - name: app-demo
          image: nginx

          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-svc
  namespace: app-demo
  labels:
    app: app-demo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: app-demo
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: argocd
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubesphere.io/creator: admin
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/service-upstream: 'true'
spec:
  tls:
    - hosts:
        - argocd.hotanloc.xyz
      secretName: argocd-hggk7
  rules:
    - host: argocd.hotanloc.xyz
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
---
      
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: app-demo-cert
#   namespace: app-demo
# spec:
#   secretName: letsencrypt-prod
#   issuerRef:
#     name: letsencrypt-production
#     kind: ClusterIssuer
#   commonName: "app-demo.hotanloc.xyz"
#   dnsNames:
#     - "app-demo.hotanloc.xyz"
